# Generated by Django 5.2.7 on 2025-10-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(default=25)),
                ('completed', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
